const deck = [
    {
      name: "Bulbasaur",
      damage: 40,
      imgsrc: 'assets/Bulbasaur.jpg',
    }, {
      name: "Caterpie",
      damage: 30,
      imgsrc: './assets/Caterpie.jpg',
    }, {
      name: "Charmander",
      damage: 30,
      imgsrc: 'assets/Charmander.jpg',
    }, {
      name: "Clefairy",
      damage: 50,
      imgsrc: 'assets/Clefairy.jpg',
    }, {
      name: "Jigglypuff",
      damage: 50,
      imgsrc: 'assets/jiggalypuff.jpg',
    }, {
      name: "Mankey",
      damage: 30,
      imgsrc: 'assets/mankey.jpg'
    }, {
      name: "Meowth",
      damage: 50,
      imgsrc: 'assets/meowth.jpg',
    }, {
      name: "Nidoran - female",
      damage: 60,
      imgsrc: 'assets/nidoran-F.jpg',
    }, {
      name: "Nidoran - male",
      damage: 50,
      imgsrc: 'assets/Nidoran-m.jpg'
    }, {
      name: "Oddish",
      damage: 40,
      imgsrc: 'assets/oddish.jpg',
    }, {
      name: "Pidgey",
      damage: 30,
      imgsrc: 'assets/pidgey.jpg',
    }, {
      name: "Pikachu",
      damage: 60,
      imgsrc: 'assets/pikachu.jpg',
    }, {
      name: "Poliwag",
      damage: 40,
      imgsrc: 'assets/poliwag.jpg'
    }, {
      name: "Psyduck",
      damage: 60,
      imgsrc: 'assets/psyduck.jpg'
    }, {
      name: "Rattata",
      damage: 20,
      imgsrc: 'assets/rattatat.jpg'
    }, {
      name: "Squirtle",
      damage: 30,
      imgsrc: 'assets/squirtle.jpeg',
    }, {
      name: "Vulpix",
      damage: 40,
      imgsrc: 'assets/vulpix.jpg'
    }, {
      name: "Weedle", 
      damage: 30,
      imgsrc: 'assets/weedle.jpg'
    }, {
      name: "Alakazam",
      damage: 60,
      imgsrc: 'assets/alakazam.jpg'
    }, {
      name: "Gyarados",
      damage: 60,
      imgsrc: 'assets/Gyarados.jpg'
    }, {
      name: "Staryu",
      damage: 40,
      imgsrc: 'assets/Staryu.jpg'
    }, {
      name: "Porygon",
      damage: 40,
      imgsrc: 'assets/Porygon.jpg'
    }, {
      name: "Abra",
      damage: 30,
      imgsrc: 'assets/Abra.jpg'
    }, {
      name: "Voltorb",
      damage: 20,
      imgsrc: 'assets/Voltorb.jpg'
    }, {
      name: "Beedrill",
      damage: 60,
      imgsrc: 'assets/Beedrill.jpg'
    }, {
      name: "Gastly",
      damage: 40,
      imgsrc: 'assets/Gastly.jpg'
    }, {
      name: "Farfetchd",
      damage: 50,
      imgsrc: 'assets/Farfetchd.jpg'
    }, {
      name: "Magikarp",
      damage: 0,
      imgsrc: 'assets/Magikarp.jpg'
    }, {
      name: "Dragonair",
      damage: 60,
      imgsrc: 'assets/Dragonair.jpg'
    }, {
      name: "Blastoise",
      damage: 60,
      imgsrc: 'assets/Blastoise.jpg'
    }, {
      name: "Dratini",
      damage: 30,
      imgsrc: 'assets/Dratini.jpg'
    }, {
      name: "Charmeleon",
      damage: 40,
      imgsrc: 'assets/Charmeleon.jpg'
    }, 
  ]

  export default deck